# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'arayuz.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1160, 530)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 170, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 170, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 170, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 170, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        Form.setPalette(palette)
        self.tableWidget = QtWidgets.QTableWidget(Form)
        self.tableWidget.setGeometry(QtCore.QRect(420, 20, 721, 301))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.BtnDYukle = QtWidgets.QPushButton(Form)
        self.BtnDYukle.setGeometry(QtCore.QRect(620, 380, 261, 81))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.BtnDYukle.setFont(font)
        self.BtnDYukle.setObjectName("BtnDYukle")
        self.BtnANN = QtWidgets.QPushButton(Form)
        self.BtnANN.setGeometry(QtCore.QRect(30, 330, 261, 81))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.BtnANN.setFont(font)
        self.BtnANN.setObjectName("BtnANN")
        self.BtnKNN = QtWidgets.QPushButton(Form)
        self.BtnKNN.setGeometry(QtCore.QRect(30, 30, 261, 81))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.BtnKNN.setFont(font)
        self.BtnKNN.setObjectName("BtnKNN")
        self.BtnNaive = QtWidgets.QPushButton(Form)
        self.BtnNaive.setGeometry(QtCore.QRect(30, 230, 261, 81))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.BtnNaive.setFont(font)
        self.BtnNaive.setObjectName("BtnNaive")
        self.BtnRandomForest = QtWidgets.QPushButton(Form)
        self.BtnRandomForest.setGeometry(QtCore.QRect(30, 130, 261, 81))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.BtnRandomForest.setFont(font)
        self.BtnRandomForest.setObjectName("BtnRandomForest")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.BtnDYukle.setText(_translate("Form", "VERISETINI GOSTER"))
        self.BtnANN.setText(_translate("Form", "ANN"))
        self.BtnKNN.setText(_translate("Form", "KNN"))
        self.BtnNaive.setText(_translate("Form", "NAIVE"))
        self.BtnRandomForest.setText(_translate("Form", "RANDOM FOREST"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
