# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'decision_tree.ui'
##
## Created by: Qt User Interface Compiler version 6.6.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QHeaderView, QLabel, QLineEdit,
    QPushButton, QSizePolicy, QTableWidget, QTableWidgetItem,
    QWidget)

class Ui_Form(object):
    def setupUi(self, Form):
        if not Form.objectName():
            Form.setObjectName(u"Form")
        Form.resize(667, 715)
        palette = QPalette()
        brush = QBrush(QColor(255, 255, 255, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Base, brush)
        brush1 = QBrush(QColor(0, 170, 127, 255))
        brush1.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Window, brush1)
        palette.setBrush(QPalette.Inactive, QPalette.Base, brush)
        palette.setBrush(QPalette.Inactive, QPalette.Window, brush1)
        palette.setBrush(QPalette.Disabled, QPalette.Base, brush1)
        palette.setBrush(QPalette.Disabled, QPalette.Window, brush1)
        Form.setPalette(palette)
        self.veri_egit = QPushButton(Form)
        self.veri_egit.setObjectName(u"veri_egit")
        self.veri_egit.setGeometry(QRect(10, 470, 251, 51))
        font = QFont()
        font.setPointSize(10)
        font.setBold(True)
        self.veri_egit.setFont(font)
        self.BtnEgit = QPushButton(Form)
        self.BtnEgit.setObjectName(u"BtnEgit")
        self.BtnEgit.setGeometry(QRect(530, 80, 93, 28))
        self.TxtAgacDerinligi = QLineEdit(Form)
        self.TxtAgacDerinligi.setObjectName(u"TxtAgacDerinligi")
        self.TxtAgacDerinligi.setGeometry(QRect(530, 50, 113, 22))
        self.LblAgacDerinligi = QLabel(Form)
        self.LblAgacDerinligi.setObjectName(u"LblAgacDerinligi")
        self.LblAgacDerinligi.setGeometry(QRect(400, 50, 121, 21))
        font1 = QFont()
        font1.setPointSize(9)
        self.LblAgacDerinligi.setFont(font1)
        self.LblDeneme = QLabel(Form)
        self.LblDeneme.setObjectName(u"LblDeneme")
        self.LblDeneme.setGeometry(QRect(370, 530, 371, 51))
        self.TxtTestOrani = QLineEdit(Form)
        self.TxtTestOrani.setObjectName(u"TxtTestOrani")
        self.TxtTestOrani.setGeometry(QRect(1090, 700, 113, 22))
        self.label = QLabel(Form)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(790, 700, 61, 71))
        font2 = QFont()
        font2.setPointSize(18)
        self.label.setFont(font2)
        self.LblPrecision = QLabel(Form)
        self.LblPrecision.setObjectName(u"LblPrecision")
        self.LblPrecision.setGeometry(QRect(1120, 840, 171, 31))
        font3 = QFont()
        font3.setFamilies([u"Nirmala UI"])
        font3.setPointSize(10)
        self.LblPrecision.setFont(font3)
        self.LblRecall = QLabel(Form)
        self.LblRecall.setObjectName(u"LblRecall")
        self.LblRecall.setGeometry(QRect(1120, 880, 171, 31))
        self.LblRecall.setFont(font3)
        self.TxtEgit = QPushButton(Form)
        self.TxtEgit.setObjectName(u"TxtEgit")
        self.TxtEgit.setGeometry(QRect(1230, 700, 93, 61))
        self.LblDeneme_2 = QLabel(Form)
        self.LblDeneme_2.setObjectName(u"LblDeneme_2")
        self.LblDeneme_2.setGeometry(QRect(730, 1110, 371, 51))
        self.LblF1Score = QLabel(Form)
        self.LblF1Score.setObjectName(u"LblF1Score")
        self.LblF1Score.setGeometry(QRect(1120, 920, 171, 31))
        self.LblF1Score.setFont(font3)
        self.LblKomsulukDegeri = QLabel(Form)
        self.LblKomsulukDegeri.setObjectName(u"LblKomsulukDegeri")
        self.LblKomsulukDegeri.setGeometry(QRect(970, 740, 121, 21))
        self.LblKomsulukDegeri.setFont(font1)
        self.tableWidget_2 = QTableWidget(Form)
        self.tableWidget_2.setObjectName(u"tableWidget_2")
        self.tableWidget_2.setGeometry(QRect(710, 800, 391, 311))
        self.TxtKomsulukDegeri = QLineEdit(Form)
        self.TxtKomsulukDegeri.setObjectName(u"TxtKomsulukDegeri")
        self.TxtKomsulukDegeri.setGeometry(QRect(1090, 740, 113, 22))
        self.LblSpecificity = QLabel(Form)
        self.LblSpecificity.setObjectName(u"LblSpecificity")
        self.LblSpecificity.setGeometry(QRect(1120, 960, 171, 31))
        self.LblSpecificity.setFont(font3)
        self.veri_egit_2 = QPushButton(Form)
        self.veri_egit_2.setObjectName(u"veri_egit_2")
        self.veri_egit_2.setGeometry(QRect(710, 1180, 251, 51))
        self.veri_egit_2.setFont(font)
        self.LblTestOrani = QLabel(Form)
        self.LblTestOrani.setObjectName(u"LblTestOrani")
        self.LblTestOrani.setGeometry(QRect(990, 700, 81, 16))
        self.LblTestOrani.setFont(font1)
        self.LblAccuracy = QLabel(Form)
        self.LblAccuracy.setObjectName(u"LblAccuracy")
        self.LblAccuracy.setGeometry(QRect(1120, 800, 171, 31))
        self.LblAccuracy.setFont(font3)
        self.LblPrecision_2 = QLabel(Form)
        self.LblPrecision_2.setObjectName(u"LblPrecision_2")
        self.LblPrecision_2.setGeometry(QRect(450, 210, 171, 31))
        self.LblPrecision_2.setFont(font3)
        self.LblRecall_2 = QLabel(Form)
        self.LblRecall_2.setObjectName(u"LblRecall_2")
        self.LblRecall_2.setGeometry(QRect(450, 250, 171, 31))
        self.LblRecall_2.setFont(font3)
        self.LblSpecificity_2 = QLabel(Form)
        self.LblSpecificity_2.setObjectName(u"LblSpecificity_2")
        self.LblSpecificity_2.setGeometry(QRect(450, 300, 171, 31))
        self.LblSpecificity_2.setFont(font3)
        self.LblAccuracy_2 = QLabel(Form)
        self.LblAccuracy_2.setObjectName(u"LblAccuracy_2")
        self.LblAccuracy_2.setGeometry(QRect(450, 170, 171, 31))
        self.LblAccuracy_2.setFont(font3)
        self.label_2 = QLabel(Form)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(20, 132, 321, 301))

        self.retranslateUi(Form)

        QMetaObject.connectSlotsByName(Form)
    # setupUi

    def retranslateUi(self, Form):
        Form.setWindowTitle(QCoreApplication.translate("Form", u"Form", None))
        self.veri_egit.setText(QCoreApplication.translate("Form", u"SATIR EGIT", None))
        self.BtnEgit.setText(QCoreApplication.translate("Form", u"EGIT", None))
        self.LblAgacDerinligi.setText(QCoreApplication.translate("Form", u"A\u011fa\u00e7 Derinli\u011fi", None))
        self.LblDeneme.setText(QCoreApplication.translate("Form", u"TextLabel", None))
        self.label.setText(QCoreApplication.translate("Form", u"KNN", None))
        self.LblPrecision.setText("")
        self.LblRecall.setText("")
        self.TxtEgit.setText(QCoreApplication.translate("Form", u"EGIT", None))
        self.LblDeneme_2.setText(QCoreApplication.translate("Form", u"TextLabel", None))
        self.LblF1Score.setText("")
        self.LblKomsulukDegeri.setText(QCoreApplication.translate("Form", u"Kom\u015fuluk de\u011feri :", None))
        self.LblSpecificity.setText("")
        self.veri_egit_2.setText(QCoreApplication.translate("Form", u"SATIR EGIT", None))
        self.LblTestOrani.setText(QCoreApplication.translate("Form", u"Test Oran\u0131 :", None))
        self.LblAccuracy.setText("")
        self.LblPrecision_2.setText("")
        self.LblRecall_2.setText("")
        self.LblSpecificity_2.setText("")
        self.LblAccuracy_2.setText("")
        self.label_2.setText(QCoreApplication.translate("Form", u"TextLabel", None))
    # retranslateUi

